class_mapping = {
    0: "Corals",
    1: "Crabs",
    2: "Dolphin",
    3: "Eel",
    4: "Jelly Fish",
    5: "Lobster",
    6: "Nudibranchs",
    7: "Octopus",
    8: "Penguin",
    9: "Puffers",
    10: "Sea Rays",
    11: "Sea Urchins",
    12: "Seahorse",
    13: "Seal",
    14: "Sharks",
    15: "Squid",
    16: "Starfish",
    17: "Turtle_Tortoise",
    18: "Whale",
}