class_mapping = {
    0: "Clams",
    1: "Corals",
    2: "Crabs",
    3: "Dolphin",
    4: "Eel",
    5: "Fish",
    6: "Jelly Fish",
    7: "Lobster",
    8: "Nudibranchs",
    9: "Octopus",
    10: "Otter",
    11: "Penguin",
    12: "Puffers",
    13: "Sea Rays",
    14: "Sea Urchins",
    15: "Seahorse",
    16: "Seal",
    17: "Sharks",
    18: "Shrimp",
    19: "Squid",
    20: "Starfish",
    21: "Turtle_Tortoise",
    22: "Whale",
}
